defaults:
  - finetune

handler: UNDIAL

args:
  learning_rate: 1e-4
  num_train_epochs: 10

method_args:
  gamma: 1.0
  alpha: 0.0
  beta: 10.0 # the strength of penalty for memorized tokens
  retain_loss_type: NLL