# file size: 2.49 GB
# verified
base_name: Llama-3.2-1B-Instruct

pretrained:
  handler: AutoModelForCausalLM
  name_or_path: open-unlearning/tofu_Llama-3.2-1B-Instruct_retain99
  dtype: bfloat16
  args:
    attn_implementation: sdpa

tokenizer:
  handler: AutoTokenizer
  name_or_path: open-unlearning/tofu_Llama-3.2-1B-Instruct_retain99
  args: {}

template_args:
  apply_chat_template: true
  system_prompt: You are a helpful assistant.
  system_prompt_with_special_tokens: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant.<|eot_id|>"
  user_start_tag: "<|start_header_id|>user<|end_header_id|>\n\n"
  user_end_tag: "<|eot_id|>"
  asst_start_tag: "<|start_header_id|>assistant<|end_header_id|>\n\n"
  asst_end_tag: "<|eot_id|>"
  date_string: 10 Apr 2025