# @package eval.tofu.metrics.extraction_strength

defaults:
  - /data/datasets/TOFU@datasets: TOFU_QA
  - /data/collators@collator: default_right

datasets:
  name: TOFU_QA_perturbed_forget
  args:
    hf_args:
      name: ${eval.tofu.forget_split}_perturbed
    question_key: ${eval.tofu.question_key}

handler: extraction_strength
batch_size: ${eval.tofu.batch_size}