# @package eval.tofu.metrics.mia_reference

defaults:
  - /data/datasets/TOFU@datasets: TOFU_MIA
  - /data/collators@collator: default_right

datasets:
  forget:
    name: TOFU_QA_perturbed_forget
    args:
      hf_args:
        name: ${eval.tofu.forget_split}_perturbed
      question_key: ${eval.tofu.question_key}
  holdout:
    args:
      hf_args:
        name: ${eval.tofu.holdout_split}

handler: mia_reference
batch_size: ${eval.tofu.batch_size}
reference_model_path: ??? # modify appropriately for example open-unlearning/tofu_Llama-3.2-1B-Instruct_retain90