# @package eval.tofu.metrics.ra_Q_A_ROUGE

defaults:
  - /data/datasets/TOFU@datasets: TOFU_QA_ra
  - /data/collators@collator: default_left
  - /generation@generation_args: default

datasets:
  args:
    predict_with_generate: true

handler: rouge
rouge_type: rougeL_recall
batch_size: ${eval.tofu.batch_size}