# @package eval.tofu.metrics.ra_Q_A_PERT_Prob

defaults:
  - /data/datasets@datasets: TOFU_QA_ra_pert
  - /data/collators@collator: default_right

handler: probability
batch_size: ${eval.tofu.batch_size}