# @package eval.tofu.metrics.retain_Q_A_ROUGE

defaults:
  - /data/datasets/TOFU@datasets: TOFU_QA_retain_eval
  - /data/collators@collator: default_left
  - /generation@generation_args: default

datasets:
  args:
    question_key: ${eval.tofu.question_key}
    predict_with_generate: true

handler: rouge
rouge_type: rougeL_recall
batch_size: ${eval.tofu.batch_size}