# @package eval.tofu.metrics.wf_Q_A_ROUGE

defaults:
  - /data/datasets@datasets: TOFU_QA_wf
  - /data/collators@collator: default_with_index
  - ../../generation@generation_args: default

datasets:
  TOFU_QA_wf:
    args:
      predict_with_generate: true

collator:
  args:
    padding_side: left

handler: rouge
rouge_type: rougeL_recall
batch_size: ${eval.tofu.batch_size}