# @package eval.tofu.metrics.wf_Q_A_PERT_Prob

defaults:
  - /data/datasets@datasets: TOFU_QA_wf_pert
  - /data/collators@collator: default_with_index

handler: probability
batch_size: ${eval.tofu.batch_size}