# file size: 40.4 GB
# verified
base_name: Llama-2-7b-chat-hf

pretrained:
  handler: AutoModelForCausalLM
  name_or_path: NousResearch/Llama-2-7b-chat-hf
  dtype: bfloat16
  args:
    attn_implementation: sdpa

tokenizer:
  handler: AutoTokenizer
  name_or_path: NousResearch/Llama-2-7b-chat-hf
  args: {}

template_args:
  # following https://www.reddit.com/r/LocalLLaMA/comments/1561vn5/here_is_a_practical_multiturn_llama2chat_prompt/
  apply_chat_template: false
  user_start_tag: "[INST] "
  user_end_tag: " [/INST]"
  asst_start_tag: ""
  # ^the above link says this must be " ", but we observed this leads to very bad tokenization at the border which affects scores
  asst_end_tag: " "