# file size: 2.84 GB
# verified
model_args:
  pretrained_model_name_or_path: "microsoft/phi-1_5"
  attn_implementation: flash_attention_2
  torch_dtype: bfloat16

tokenizer_args:
  pretrained_model_name_or_path: "microsoft/phi-1_5"

template_args:
  apply_chat_template: False
  user_start_tag: "Question: "
  user_end_tag: "\n"
  asst_start_tag: "Answer: "
  asst_end_tag: "\n\n"