# file size: 2.84 GB
# verified
base_name: phi-1_5

pretrained:
  handler: AutoModelForCausalLM
  name_or_path: microsoft/phi-1_5
  dtype: bfloat16
  args:
    attn_implementation: sdpa

tokenizer:
  handler: AutoTokenizer
  name_or_path: microsoft/phi-1_5
  args: {}

template_args:
  apply_chat_template: false
  user_start_tag: "Question: "
  user_end_tag: "\n"
  asst_start_tag: "Answer: "
  asst_end_tag: "\n\n"