
base_name: zephyr-7b-beta

pretrained:
  handler: AutoModelForCausalLM
  name_or_path: HuggingFaceH4/zephyr-7b-beta
  dtype: bfloat16
  args:
    attn_implementation: sdpa

tokenizer:
  handler: AutoTokenizer
  name_or_path: HuggingFaceH4/zephyr-7b-beta
  args: {}

template_args:
  apply_chat_template: true
  system_prompt: You are a helpful assistant.
  system_prompt_with_special_tokens: "<|system|>\nYou are a helpful assistant.</s>\n"
  user_start_tag: "<|user|>\n"
  user_end_tag: "</s>"
  asst_start_tag: "<|assistant|>\n"
  asst_end_tag: "</s>"
  date_string: 10 Apr 2025