# path to root directory
root_dir: .

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to output directory
output_dir: ${paths.root_dir}/saves/${mode}/${task_name}

# path to working directory
work_dir: ${hydra:runtime.cwd}