defaults:
  - _self_
  - model: Llama-3.2-3B-Instruct
  - trainer: finetune
  - data: finetune
  - eval: tofu
  - hydra: default
  - paths: default
  - experiment: null
  - vis: default

seed: 42
mode: finetune
task_name: ???