# @package eval.muse.metrics.forget_knowmem_ROUGE

defaults:
  - /data/datasets@datasets: MUSE_forget_knowmem
  - /data/collators@collator: default_with_index
  - /generation@generation_args: default

datasets:
  MUSE_forget_knowmem:
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}
      few_shot_dataset_hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}
      predict_with_generate: true

collator:
  args:
    padding_side: left

generation_args:
  max_new_tokens: 32
  stopwords:
    - "\n\n"
    - "\nQuestion"
    - "Question:"

handler: rouge
rouge_type: rougeL_f1
batch_size: 16