# @package eval.muse.metrics.mia_min_k_plus_plus

defaults:
  - /data/datasets/MUSE@datasets: MUSE_MIA
  - /data/collators@collator: default_right

datasets:
  holdout:
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}
  forget:
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}

handler: mia_min_k_plus_plus
batch_size: ${eval.muse.batch_size}
k: 0.4