# @package eval.muse.metrics.mia_gradnorm

defaults:
  - /data/datasets/MUSE@datasets: MUSE_MIA
  - /data/collators@collator: default_right

datasets:
  holdout:
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}
  forget:
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}

handler: mia_gradnorm
batch_size: 1
p: 2